[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.armv7-unknown-linux-gnueabi]
linker = "arm-linux-gnueabi-gcc"

[target.armv7-unknown-linux-musleabi]
linker = "arm-linux-gnueabi-gcc"


[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-gnueabi-gcc"
